### ISSUE TITLE
Request for adding AMISR dataset

### ISSUE THREAD

**Issue by yonghuier** [JouleCai/geospacelab#10]
Great job! AMISR has excellent data in the polar region. I was wondering how I could  add the AMISR dataset to the project? Thank you!

**Comment by JouleCai** [comment]
Hi, thank you for your interest in GeospaceLAB. We have a plan to add Poker flat radar data in the near future. The Resolute Bay radar data may be added as well. The data will be obtained from the Madrigal database. I will let you know when the basic module is ready. Then you can add additional functions if needed. I feel this way is easier for getting in touch with the development of the package.
