### ISSUE TITLE
Not able to add MAG_LAT and MAgG_LON  in addtional x-axis 

### ISSUE THREAD

**Issue by ankushbhaskar** [JouleCai/geospacelab#13]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[24], line 98
     89 layout = [
     90         #[v_i_H, v_i_V],
     91         #[d_B_P, d_B_D, d_B_F],
   (...)
     95         [jE_i],
     96 ]
     97 db_dmsp.set_layout(panel_layouts=layout)#, left=0.1, right=0.45, top=1, hspace=0.0)
---> 98 db_dmsp.draw()
     99 # uts = db_dmsp.search_UTs(AACGM_LAT=66.6, GEO_LON=[8, 32])
    100 # if list(uts):
    101 #     db_dmsp.add_vertical_line(uts[0])
    102 # uts = db_dmsp.search_UTs(AACGM_LAT=75.4, GEO_LON=[0, 30])
    103 # if list(uts):
    104 #     db_dmsp.add_vertical_line(uts[0])
    105 db_dmsp.add_panel_labels()

File ~/anaconda3/lib/python3.9/site-packages/geospacelab/visualization/mpl/dashboards.py:156, in TSDashboard.draw(self, dt_fr, dt_to, auto_grid, time_res)
    154     plot_layout = self.panel_layouts[npanel]
    155     plot_layout = self._validate_plot_layout(plot_layout)
--> 156     panel.draw(plot_layout)
    157     npanel = npanel + 1
    159 if auto_grid:

File ~/anaconda3/lib/python3.9/site-packages/geospacelab/visualization/mpl/panels.py:87, in TSPanel.draw(self, plot_layout, ax)
     86 def draw(self, plot_layout, ax=None):
---> 87     self.overlay_from_variables(plot_layout, ax=ax)

File ~/anaconda3/lib/python3.9/site-packages/geospacelab/visualization/mpl/panels.py:140, in TSPanel.overlay_from_variables(self, layout_in, ax, level)
    138     if self.axes_overview[ax]['colorbar'] == 'on':
    139         self._check_colorbar(ax)
--> 140     self._set_xaxis(ax=ax)
    142 self._set_yaxis(ax=ax)
    143 return iplts

File ~/anaconda3/lib/python3.9/site-packages/geospacelab/visualization/mpl/panels.py:352, in TSPanel._set_xaxis(self, ax)
    350 ax.xaxis.set_minor_locator(minorlocator)
    351 if self.bottom_panel:
--> 352     self._set_xaxis_ticklabels(ax, majorformatter=majorformatter)

File ~/anaconda3/lib/python3.9/site-packages/geospacelab/visualization/mpl/panels.py:398, in TSPanel._set_xaxis_ticklabels(self, ax, majorformatter)
    396     y0 = var_for_config.dataset[label].value
    397 else:
--> 398     raise KeyError
    399 if 'MLT' in label.upper():
    400     y0_sin = np.sin(y0 / 24. * 2 * np.pi)

KeyError:

**Comment by JouleCai** [comment]
Can you post the full script of your code and remove the line numbers?

**Comment by ankushbhaskar** [comment]
# Licensed under the BSD 3-Clause License
# Copyright (C) 2021 GeospaceLab (geospacelab)
# Author: Lei Cai, Space Physics and Astronomy, University of Oulu

__author__ = "Lei Cai"
__copyright__ = "Copyright 2021, GeospaceLab"
__license__ = "BSD-3-Clause License"
__email__ = "lei.cai@oulu.fi"
__docformat__ = "reStructureText"


import datetime
import numpy as np

from geospacelab.visualization.mpl.dashboards import TSDashboard
import geospacelab.visualization.mpl.geomap.geodashboards as geomap
import matplotlib.pyplot  as plt
dmsp_dn = datetime.datetime.strptime('20230423' + '191500', '%Y%m%d%H%M%S')
dmsp_sat_id = 'f18'
dmsp_orbit_id = None
pole='N'
band = 'LBHS'
dt_fr = dmsp_dn - datetime.timedelta(minutes=30)
dt_to = dmsp_dn + datetime.timedelta(minutes=30)
time_c = dmsp_dn
sat_id = dmsp_sat_id
orbit_id = dmsp_orbit_id

# Create a geodashboard object
dashboard = geomap.GeoDashboard(dt_fr=dt_fr, dt_to=dt_to, figure_config={'figsize': (10, 10)})

# If the orbit_id is specified, only one file will be downloaded. This option saves the downloading time.
# dashboard.dock(datasource_contents=['jhuapl', 'dmsp', 'ssusi', 'edraur'], pole='N', sat_id='f17', orbit_id='46863')
# If not specified, the data during the whole day will be downloaded.
ds_dmsp_ssusi_edr = dashboard.dock(datasource_contents=['jhuapl', 'dmsp', 'ssusi', 'edraur'],
                                       pole=pole, sat_id=sat_id, orbit_id=orbit_id)
ds_dmsp_ssusi_disk = dashboard.dock(datasource_contents=['jhuapl', 'dmsp', 'ssusi', 'sdrdisk'],
                                        pole=pole, sat_id=sat_id, orbit_id=orbit_id, pp_type='DAY_AURORAL')
ds_s1 = dashboard.dock(
datasource_contents=['madrigal', 'satellites', 'dmsp', 's1'],
dt_fr=time_c - datetime.timedelta(minutes=30),
dt_to=time_c + datetime.timedelta(minutes=30),
sat_id=sat_id, replace_orbit=True)
    
# ds_swarm = dashboard.dock(datasource_contents=['tud', 'swarm', 'dns_pod'], sat_id=swarm_sat_id, add_AACGM=True)

dashboard.set_layout(1, 1, left=0.0, right=1.0, top=0.9, bottom=0.1, wspace=0)
    
# Add the first polar map
# Get the variables: LBHS emission intensiy, corresponding times and locations
lbhs = dashboard.assign_variable('GRID_AUR_' + band, dataset=ds_dmsp_ssusi_edr)
dts = dashboard.assign_variable('DATETIME', dataset=ds_dmsp_ssusi_edr)
dts = dts.value.flatten()
mlat = dashboard.assign_variable('GRID_MLAT', dataset=ds_dmsp_ssusi_edr)
mlon = dashboard.assign_variable('GRID_MLON', dataset=ds_dmsp_ssusi_edr)
mlt = dashboard.assign_variable(('GRID_MLT'), dataset=ds_dmsp_ssusi_edr)

   
# Lower panels
# on the left side
diff_minutes = 16
dt_fr = dmsp_dn - datetime.timedelta(minutes=diff_minutes / 2)
dt_to = dmsp_dn + datetime.timedelta(minutes=diff_minutes / 2)
db_dmsp = TSDashboard(dt_fr=dt_fr, dt_to=dt_to, figure=dashboard.figure,
                              timeline_extra_labels=['GEO_LAT', 'GEO_LON', 'MAG_LAT', 'MAG_LON'])

dataset_s1 = db_dmsp.dock(datasource_contents=['madrigal', 'satellites', 'dmsp', 's1'], sat_id=sat_id)
dataset_s4 = db_dmsp.dock(datasource_contents=['madrigal', 'satellites', 'dmsp', 's4'], sat_id=sat_id)
dataset_e = db_dmsp.dock(datasource_contents=['madrigal', 'satellites', 'dmsp', 'e'], sat_id=sat_id)

n_e = db_dmsp.assign_variable('n_e', dataset=dataset_s1)
v_i_H = db_dmsp.assign_variable('v_i_H', dataset=dataset_s1)
v_i_V = db_dmsp.assign_variable('v_i_V', dataset=dataset_s1)
d_B_D = db_dmsp.assign_variable('d_B_D', dataset=dataset_s1)
d_B_P = db_dmsp.assign_variable('d_B_P', dataset=dataset_s1)
d_B_F = db_dmsp.assign_variable('d_B_F', dataset=dataset_s1)

JE_e = db_dmsp.assign_variable('JE_e', dataset=dataset_e)
JE_i = db_dmsp.assign_variable('JE_i', dataset=dataset_e)
jE_e = db_dmsp.assign_variable('jE_e', dataset=dataset_e)
jE_i = db_dmsp.assign_variable('jE_i', dataset=dataset_e)
E_e_MEAN = db_dmsp.assign_variable('E_e_MEAN', dataset=dataset_e)
E_i_MEAN = db_dmsp.assign_variable('E_i_MEAN', dataset=dataset_e)
#print(JE_e)
T_i = db_dmsp.assign_variable('T_i', dataset=dataset_s4)
T_e = db_dmsp.assign_variable('T_e', dataset=dataset_s4)
c_O_p = db_dmsp.assign_variable('COMP_O_p', dataset=dataset_s4)

layout = [
        #[v_i_H, v_i_V],
        #[d_B_P, d_B_D, d_B_F],
        #[E_e_MEAN, E_i_MEAN],
        [JE_e, JE_i],
        [jE_e],
        [jE_i],
]
db_dmsp.set_layout(panel_layouts=layout)#, left=0.1, right=0.45, top=1, hspace=0.0)
db_dmsp.draw()
# uts = db_dmsp.search_UTs(AACGM_LAT=66.6, GEO_LON=[8, 32])
# if list(uts):
#     db_dmsp.add_vertical_line(uts[0])
# uts = db_dmsp.search_UTs(AACGM_LAT=75.4, GEO_LON=[0, 30])
# if list(uts):
#     db_dmsp.add_vertical_line(uts[0])
db_dmsp.add_panel_labels()
#plt.savefig('DMSP_f18__23_apr_2023_1907_1923.pdf', dpi=100 )
    # On the right side
    #delta_t = 12
    #dt_fr = swarm_dn - datetime.timedelta(minutes=delta_t)
    #dt_to = swarm_dn + datetime.timedelta(minutes=delta_t)

**Comment by ankushbhaskar** [comment]
In this  'MAG_LAT', 'MAG_LON' giving errors, however, AACGM_LAT and AACGM_LON working

**Comment by JouleCai** [comment]
You got it. Please refer to the latest verion of the example code.

**Comment by ankushbhaskar** [comment]
Hi sorry to bother you, but I want to add MAG_LAT', 'MAG_LON', and magnetic dipole coordinates not AACGM, but it is giving a key error, can you tell me how to fix this?  Thanks.

**Comment by JouleCai** [comment]
> Hi sorry to bother you, but I want to add MAG_LAT', 'MAG_LON', and magnetic dipole coordinates not AACGM, but it is giving a key error, can you tell me how to fix this? Thanks.

To do so, you need to add those keys in the dependence of the last variable in the panel layout:
After set panel layout, add

```python
jE_i.depends[0]['MAG_LAT'] = jE_i.depends[0]['AACGM_LAT']
jE_i.depends[0]['MAG_LON'] = jE_i.depends[0]['AACGM_LON']
```

Note that the AACGM coordinates are used and only the labels are changed.

**Comment by ankushbhaskar** [comment]
Great that was helpful thank you so much!
