### ISSUE TITLE
network problem 

### ISSUE THREAD

**Issue by Ryannok** [JouleCai/geospacelab#15]
Hi, I always have Internal Server Error problems when downloading DMSP data, how can I download the required data locally? Thanks

**Comment by JouleCai** [comment]
Can you post your code and the text of the errors?

**Comment by Ryannok** [comment]
Hi, I wanted to get the energy spectra of electrons and ions, so I tried the routines in your codebase

import datetime
from geospacelab.express.dmsp_dashboard import DMSPTSDashboard
def show_dmsp():
    sat_id = 'f16'
    dt_c = datetime.datetime(2010, 10, 5, 14, 43)
    diff_minutes = 8
    dt_fr = dt_c - datetime.timedelta(minutes=diff_minutes/2)
    dt_to = dt_c + datetime.timedelta(minutes=diff_minutes/2)

    dashboard = DMSPTSDashboard(
        dt_fr, dt_to, sat_id=sat_id,
    )
    dashboard.quicklook()
    dashboard.save_figure()
    dashboard.show()
if __name__ == '__main__':
    show_dmsp()

But then, I ran into the following problem：

Create a new figure: Figure(1000x1000).
Cannot find the requested data file in C:\dmsp\Madrigal\DMSP\201010\20101005
Searching data from the Madrigal database ...
Downloading  dms_20101005_16s1.001.hdf5 from the Madrigal database ...
HTTP Error 500: Internal Server Error
ERROR: The data source cannot be docked. 
Check the built-in sourced data using the method: "list_sourced_dataset". 
Or, add a temporary or user-defined dataset by the method of "add_dataset". 
Cannot find the requested data file in C:\dmsp\Madrigal\DMSP\201010\20101005
Searching data from the Madrigal database ...
Downloading  dms_20101005_16e.001.hdf5 from the Madrigal database ...
HTTP Error 500: Internal Server Error
ERROR: The data source cannot be docked. 
Check the built-in sourced data using the method: "list_sourced_dataset".
Or, add a temporary or user-defined dataset by the method of "add_dataset".
Cannot find the requested data file in C:\dmsp\Madrigal\DMSP\201010\20101005
Searching data from the Madrigal database ...
Downloading  dms_20101005_16s4.002.hdf5 from the Madrigal database ...
HTTP Error 500: Internal Server Error
ERROR: The data source cannot be docked.
Check the built-in sourced data using the method: "list_sourced_dataset".
Or, add a temporary or user-defined dataset by the method of "add_dataset".

I tried to download the data locally, but only got the dms_20101005_16e.001.hdf5 file, the other two can't be downloaded, is this a Madrigal database problem?

**Comment by JouleCai** [comment]
Hi,

This is a known issue of the API "MadrigalWeb" package connecting the Madrigal database on a Windows OS. It should work on a Linux or Mac OS. An option is that you can download the data files manually from the Madrigal database and load the files by setting the keywords "load_mode" and "data_file_paths"

For your case, the `DMSPTSDashboard` in geospacelab.express supports only the data automatically downloaded from the web database. However, you may modify the code when docking the DMSP data. For example, to dock the DMSP s1 type file, add  the keywords in

```
self.dataset_s1 = self.dock(datasource_contents=['madrigal', 'satellites', 'dmsp', 's1'], sat_id=sat_id, 
    load_mode='assigned', # switch from the default "AUTO" to "assigned" to load the local data files.
    data_file_paths=['S1_FILE_Path'], # indicate the full paths of the data files as a list.
)
```

**Comment by JouleCai** [comment]
Hi

Could you please also upgrade the package to v0.8.11? I just found a bug related to your issue and made a fix. However, I haven't tested it on a Windows OS. After upgrading, you may run the original code to download the DMSP data from the Madrigal database. Please let me know if it works or not. Thank you.

**Comment by Ryannok** [comment]
Thanks for your work, I have just updated v0.8.11 on window and now I can get all the hdf5 files needed, but the SSCWS_info_satellites.pkl file is missing, where is this file configured?

Specific questions are as follows：
Create a new figure: Figure(1000x1000).
Cannot find the requested data file in C:\dmsp\Madrigal\DMSP\201010\20101005
Searching data from the Madrigal database ...
Downloading  dms_20101005_16s1.001.hdf5 from the Madrigal database ...
Save the file as dms_20101005_16s1.001.hdf5 in the directory C:\dmsp\Madrigal\DMSP\201010\20101005
Load IGRF coefficients ...
[WinError 3] 系统找不到指定的路径。: 'C:\\dmsp\\SSCWS\\SSCWS_info_satellites.pkl'
ERROR: The data source cannot be docked.
Check the built-in sourced data using the method: "list_sourced_dataset".
Or, add a temporary or user-defined dataset by the method of "add_dataset".
Cannot find the requested data file in C:\dmsp\Madrigal\DMSP\201010\20101005
Searching data from the Madrigal database ...
Downloading  dms_20101005_16e.001.hdf5 from the Madrigal database ...
Save the file as dms_20101005_16e.001.hdf5 in the directory C:\dmsp\Madrigal\DMSP\201010\20101005
[WinError 3] 系统找不到指定的路径。: 'C:\\dmsp\\SSCWS\\SSCWS_info_satellites.pkl'
ERROR: The data source cannot be docked.
Check the built-in sourced data using the method: "list_sourced_dataset".
Or, add a temporary or user-defined dataset by the method of "add_dataset".
Cannot find the requested data file in C:\dmsp\Madrigal\DMSP\201010\20101005
Searching data from the Madrigal database ...
Downloading  dms_20101005_16s4.002.hdf5 from the Madrigal database ...
Save the file as dms_20101005_16s4.002.hdf5 in the directory C:\dmsp\Madrigal\DMSP\201010\20101005
[WinError 3] 系统找不到指定的路径。: 'C:\\dmsp\\SSCWS\\SSCWS_info_satellites.pkl'
ERROR: The data source cannot be docked.
Check the built-in sourced data using the method: "list_sourced_dataset".
Or, add a temporary or user-defined dataset by the method of "add_dataset".

**Comment by JouleCai** [comment]
Can you upgrade again to v0.8.12. If it doesn't work, add the keyword `calib_orbit=False` when calling `DMSPTSDashboard`.

**Comment by Ryannok** [comment]
Thanks for your work, when I finished updating again and set calib_orbit=False, all the problems disappeared!

**Comment by JouleCai** [comment]
Can you test without setting the keyword calib_orbit?

**Comment by Ryannok** [comment]
Yes, if  don't set the keyword calib_orbit, it will have the same problem as above.

Create a new figure: Figure(1000x1000).
Load IGRF coefficients ...
[WinError 3] 系统找不到指定的路径。: 'C:\\dmsp\\SSCWS\\SSCWS_info_satellites.pkl'
ERROR: The data source cannot be docked.
Check the built-in sourced data using the method: "list_sourced_dataset".
Or, add a temporary or user-defined dataset by the method of "add_dataset".
[WinError 3] 系统找不到指定的路径。: 'C:\\dmsp\\SSCWS\\SSCWS_info_satellites.pkl'
ERROR: The data source cannot be docked.
Check the built-in sourced data using the method: "list_sourced_dataset".
Or, add a temporary or user-defined dataset by the method of "add_dataset".
[WinError 3] 系统找不到指定的路径。: 'C:\\dmsp\\SSCWS\\SSCWS_info_satellites.pkl'
ERROR: The data source cannot be docked.
Check the built-in sourced data using the method: "list_sourced_dataset".
Or, add a temporary or user-defined dataset by the method of "add_dataset".

**Comment by JouleCai** [comment]
It seems that you don't have permission to write on the C drive. It's better to set the default root folder to somewhere in your home directory or in another drive.

**Comment by JouleCai** [comment]
Hi, could you please update the package to v0.8.14. The issue for the file path should be solved.
