### ISSUE TITLE
Bugs in the EISCAT HDF5 data loader

### ISSUE THREAD

**Issue by habtie-phys** [JouleCai/geospacelab#4]
In the file **loader.py**,  the lines that obtain the **scan mode** and **affiliation** metadata of an EISCAT experiment do not work for some of the old day experiments.   You may test it, for example, for this one; **EISCAT_2001-09-25_cp1l_60@uhf.hdf5**.

**Comment by JouleCai** [comment]
Hi, thank you. The bugs have been fixed. This is because that the data parameters in the old EISCAT data (earlier than 2002) are different from newer data. 
The modification will be available in the next version (v0.2.18 or higher).

**Comment by habtie-phys** [comment]
Thanks for the quick fix.
