### ISSUE TITLE
Initial toml file not complete

### ISSUE THREAD

**Issue by danielk333** [JouleCai/geospacelab#5]
During clean install and using non-default data folder, the entered user specific data storage folder is not entered into the created `.toml` file

**Comment by JouleCai** [comment]
Hi, this issue is probably due to the pre-existing GeospaceLab folder in your home directory. I just modified the detection method for the "data_root_dir". Please update the package to v0.3.1 or later, and try again. It's better to remove the old .toml file.

**Comment by danielk333** [comment]
Nice! Just tested and now it works flawlessly!
